# Generated by Django 5.1 on 2024-09-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_alter_userlogin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
